# Generated by Django 3.2 on 2023-12-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poly_app', '0003_auto_20231223_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_of_appointment',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
