# Generated by Django 3.2 on 2023-12-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poly_app', '0004_auto_20231224_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type_of_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poly_app.visittype'),
        ),
    ]
